version: "3"

services:
    mongo:
        image: mongo:4.4
        ports:
        - 27018:27017

    redis:
        image: redis
        ports:
        - 6380:6379

    zookeeper:
        container_name: local-zookeeper
        image: wurstmeister/zookeeper:3.4.6
        ports:
        - "2181:2181"
    kafka:
        container_name: local-kafka
        image: wurstmeister/kafka:2.12-2.3.0
        depends_on:
        - zookeeper
        ports:
        - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_CREATE_TOPICS: "tmp_topic"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
        - /Users/ram/Documents/workspace/personal/kotlin-spring-mvc/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
        ports:
        - 9090:9090
        restart: always

    grafana:
        image: grafana/grafana
        container_name: grafana
        depends_on:
        - prometheus
        ports:
        - 3000:3000
        volumes:
        - grafana_data:/var/lib/grafana
        restart: always
volumes:
    prometheus_data:
        external: true
    grafana_data:
        external: true
